### ISSUE TITLE
NZBGet Container

### ISSUE THREAD

**Issue by Landelor** [Cloudbox/Cloudbox#164] opened 2018-06-22 03:57 UTC
This container doesn't seem to build properly the first time.
I have to run ansible-playbook with the nzbget tag a second time to get it to function properly.

**Comment by desimaniac** [comment] 2018-06-22 05:21
I pushed out a fix in develop branch. Can you test that out?  

Youll need to remove the current container and delete/rename the opt folder.

**Comment by Landelor** [comment] 2018-06-23 04:58
And then run with nzbget tag or cloudbox tag?

**Comment by desimaniac** [comment] 2018-06-23 05:39
Just nzbget tag is fine.

**Comment by Landelor** [comment] 2018-06-23 07:20
Using the nzbget tag already works though. It's with initial install that it doesn't work.

**Comment by desimaniac** [comment] 2018-06-24 06:50
The issue is fixed regardless of what tag you use to install, so I'm closing this.

**Closed by desimaniac** 2018-06-24 06:50 UTC

**Comment by Landelor** [comment] 2018-06-24 12:28
Did a clean install with the change from develop. Just confirming that it is working as stated.
Regards,
